### ISSUE TITLE
firmware update problem

### ISSUE THREAD

**Issue by johnjin404** [baidu/boteye_sensor#11]
你好，我在配置boteye标准版相机驱动时遇到了一些问题，发现它提示需要升级固件（当时检测到的版本是XP2S，在/dev/video1），后来我按照你们给出的提示在这里升级固件，但是这期间遇到两个我目前解决不了的问题。
1、我执行了 Image Download [https://github.com/baidu/boteye_sensor#image-download](url)之前的步骤，没有什么问题，但是在Image Download这步中，只有用命令`./spi_test  /dev/video1  E`没有错误反馈，但是l也没有led灯亮或者闪一秒。因为它没有错误反馈，我就接着执行下面的 version_test 程序，我的命令是`./version_test  /dev/video1`，它好像提示说Buffer size does not match control size。主要是搞不懂这两个程序的运行格式，希望有一个help功能。
2、后来我无意地把连接相机那一端的线拔了，再插上时，里面红灯一直亮着，而且现在/dev/video1也没有了，只剩下电脑自带的/dev/video0，请问怎样才能修复这个？谢谢

**Comment by HansomHu** [comment]
问题1，update firmware请参考链接[https://github.com/baidu/boteye_sensor](url)，执行命令`./spi_test /dev/video*`的作用是擦除boteye的firmware，此时已经无法读取版本号，需要重新插拔usb数据线，然后运行`cyusb_linux`烧写新的firmware。
问题2，红灯一直亮，是因为firmware已经被擦除，pc自然检测不到这个video设备。
补充，更新完firmware后，可以通过`dmesg`命令看到boteye的信息，包括版本号。

**Comment by johnjin404** [comment]
非常感谢！
